global_costmap:
  global_frame: nav_map
  robot_base_frame: base_link

  update_frequency: 2.0
  publish_frequency: 1.0
  transform_tolerance: 1.0

  rolling_window: false
  track_unknown_space: true
  always_send_full_costmap: true

  # 暂时按照约 0.90 m × 0.64 m 的矩形车体设置
  footprint:
    - [0.45, 0.32]
    - [0.45, -0.32]
    - [-0.45, -0.32]
    - [-0.45, 0.32]

  footprint_padding: 0.02

  plugins:
    - name: static_layer
      type: "costmap_2d::StaticLayer"
    - name: inflation_layer
      type: "costmap_2d::InflationLayer"

  static_layer:
    map_topic: /map
    subscribe_to_updates: true
    track_unknown_space: true
    use_maximum: false

  inflation_layer:
    inflation_radius: 0.45
    cost_scaling_factor: 4.0
